name = "YaoIR"
uuid = "77e32715-2d53-453b-8330-e0520dba5551"
authors = ["Roger-luo"]
version = "0.1.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
YaoAPI = "0843a435-28de-4971-9e8b-a9641b2983a8"

[compat]
julia = "1.4"

[extras]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YaoArrayRegister = "e600142f-9330-5003-8abb-0ebd767abc51"

[targets]
test = ["Test", "FFTW", "YaoArrayRegister"]
